[package]
name = "windows-process-platform"
version = "0.1.0"
edition = "2024"
publish = false

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
  "Win32_System_Environment",
  "Win32_System_LibraryLoader",
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_JobObjects",
  "Win32_System_Threading",
] }
