export const splitWorkspaceEnglish = {
  label: "Split chats",
  add: "Add to split view",
  added: "Already in split view",
  limit: "Maximum 4 tasks",
  close: "Close this pane",
  solo: "Show only this task",
  expandComposer: "Expand composer",
  collapseComposer: "Collapse composer",
  up: "Split up",
  down: "Split down",
  left: "Split left",
  right: "Split right",
};
export const splitWorkspaceChinese = {
  label: "分屏聊天",
  add: "添加到分屏",
  added: "已在分屏中",
  limit: "最多打开 4 个任务",
  close: "关闭此分屏",
  solo: "仅显示此任务",
  expandComposer: "展开输入框",
  collapseComposer: "收起输入框",
  up: "向上分屏",
  down: "向下分屏",
  left: "向左分屏",
  right: "向右分屏",
};
